# Generated by Django 5.1.7 on 2025-05-11 04:37

from api.models.Player import validate_player_age
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField(verbose_name='Ngày thi đấu')),
                ('match_time', models.TimeField(verbose_name='Giờ thi đấu')),
                ('stadium', models.CharField(
                    max_length=100, verbose_name='Sân vận động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['round', 'match_date', 'match_time'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên cầu thủ')),
                ('birthdate', models.DateField(validators=[
                 validate_player_age], verbose_name='Ngày sinh')),
                ('player_type', models.CharField(choices=[('domestic', 'Trong nước'), (
                    'foreign', 'Ngoài nước')], max_length=10, verbose_name='Loại cầu thủ')),
                ('note', models.TextField(blank=True,
                 null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Số vòng đấu')),
                ('start_date', models.DateField(
                    verbose_name='Ngày bắt đầu vòng đấu')),
                ('end_date', models.DateField(verbose_name='Ngày kết thúc vòng đấu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên đội')),
                ('home_stadium', models.CharField(
                    max_length=100, verbose_name='Sân nhà')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score', models.PositiveIntegerField(
                    default=0, verbose_name='Bàn thắng đội nhà')),
                ('away_score', models.PositiveIntegerField(
                    default=0, verbose_name='Bàn thắng đội khách')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                 related_name='result', to='api.match', verbose_name='Trận đấu')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('A', 'Loại A'), ('B', 'Loại B'), (
                    'C', 'Loại C')], max_length=1, verbose_name='Loại bàn thắng')),
                ('minute', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(
                    0), django.core.validators.MaxValueValidator(96)], verbose_name='Thời điểm ghi bàn (phút)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='goals', to='api.match', verbose_name='Trận đấu')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='goals', to='api.player', verbose_name='Cầu thủ ghi bàn')),
            ],
            options={
                'ordering': ['match', 'minute'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='matches', to='api.round', verbose_name='Vòng đấu'),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='players', to='api.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='away_matches', to='api.team', verbose_name='Đội khách'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='home_matches', to='api.team', verbose_name='Đội nhà'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(
                fields=('round', 'home_team'), name='unique_home_team_per_round'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(
                fields=('round', 'away_team'), name='unique_away_team_per_round'),
        ),
    ]
