# Generated by Django 5.1.7 on 2025-04-03 08:10

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên đội')),
                ('home_stadium', models.CharField(max_length=100, verbose_name='Sân nhà')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên cầu thủ')),
                ('birthdate', models.DateField(validators=[api.models.validate_player_age], verbose_name='Ngày sinh')),
                ('player_type', models.CharField(choices=[('domestic', 'Trong nước'), ('foreign', 'Ngoài nước')], max_length=10, verbose_name='Loại cầu thủ')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='api.team')),
            ],
        ),
    ]
