# Generated by Django 5.1.7 on 2025-05-11 08:12

from django.db import migrations, models


def get_default_goal_types():
    return [
        ('A', 'Loại A'),
        ('B', 'Loại B'),
        ('C', 'Loại C'),
    ]


def get_default_ranking_criteria():
    return []


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('min_player_age', models.IntegerField(default=18)),
                ('max_player_age', models.IntegerField(default=35)),
                ('min_team_players', models.IntegerField(default=11)),
                ('max_team_players', models.IntegerField(default=25)),
                ('max_foreign_players', models.IntegerField(default=5)),
                ('max_goal_time', models.IntegerField(default=90)),
                ('goal_types', models.JSONField(default=get_default_goal_types)),
                ('win_points', models.IntegerField(default=3)),
                ('draw_points', models.IntegerField(default=1)),
                ('loss_points', models.IntegerField(default=0)),
                ('ranking_criteria', models.JSONField(
                    default=get_default_ranking_criteria)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(
                max_length=100, unique=True, verbose_name='Tên đội'),
        ),
    ]
