# Generated by Django 5.1.7 on 2025-05-05 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_team_player'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
