# Generated by Django 5.1.7 on 2025-05-20 14:36

from api.models.TournamentRule import get_default_goal_types, get_default_ranking_criteria
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tournamentrule_alter_team_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='note',
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.TextField(blank=True, null=True, verbose_name='Vị trí'),
        ),
        migrations.AlterField(
            model_name='tournamentrule',
            name='goal_types',
            field=models.JSONField(default=get_default_goal_types),
        ),
        migrations.AlterField(
            model_name='tournamentrule',
            name='max_foreign_players',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='tournamentrule',
            name='max_goal_time',
            field=models.IntegerField(default=96),
        ),
        migrations.AlterField(
            model_name='tournamentrule',
            name='max_player_age',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='tournamentrule',
            name='max_team_players',
            field=models.IntegerField(default=22),
        ),
        migrations.AlterField(
            model_name='tournamentrule',
            name='min_player_age',
            field=models.IntegerField(default=16),
        ),
        migrations.AlterField(
            model_name='tournamentrule',
            name='min_team_players',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='tournamentrule',
            name='ranking_criteria',
            field=models.JSONField(default=get_default_ranking_criteria),
        ),
    ]
