# Generated by Django 5.1.7 on 2025-05-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_player_note_player_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú'),
        ),
    ]
