# Generated by Django 5.1.7 on 2025-05-05 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Số vòng đấu')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu vòng đấu')),
                ('end_date', models.DateField(verbose_name='Ngày kết thúc vòng đấu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField(verbose_name='Ngày thi đấu')),
                ('match_time', models.TimeField(verbose_name='Giờ thi đấu')),
                ('stadium', models.CharField(max_length=100, verbose_name='Sân vận động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='api.team', verbose_name='Đội khách')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='api.team', verbose_name='Đội nhà')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='api.round', verbose_name='Vòng đấu')),
            ],
            options={
                'ordering': ['round', 'match_date', 'match_time'],
                'constraints': [models.UniqueConstraint(fields=('round', 'home_team'), name='unique_home_team_per_round'), models.UniqueConstraint(fields=('round', 'away_team'), name='unique_away_team_per_round')],
            },
        ),
    ]
