# Generated by Django 5.1.7 on 2025-05-05 13:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_round_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('A', 'Loại A'), ('B', 'Loại B'), ('C', 'Loại C')], max_length=1, verbose_name='Loại bàn thắng')),
                ('minute', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(96)], verbose_name='Thời điểm ghi bàn (phút)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='api.match', verbose_name='Trận đấu')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='api.player', verbose_name='Cầu thủ ghi bàn')),
            ],
            options={
                'ordering': ['match', 'minute'],
            },
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score', models.PositiveIntegerField(default=0, verbose_name='Bàn thắng đội nhà')),
                ('away_score', models.PositiveIntegerField(default=0, verbose_name='Bàn thắng đội khách')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='api.match', verbose_name='Trận đấu')),
            ],
        ),
    ]
